name: Hello World Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  issues: write


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Create new branch
        run: |
          git checkout -b release-${{ inputs.version }} tags/${{ inputs.version }}
          git push origin release-${{ inputs.version }}
  
      - name: Verify branch creation
        run: git ls-remote --heads origin release-${{ inputs.version }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: release-${{ inputs.version }}"
          title: "chore: release-${{ inputs.version }}"
          body: "chore: release-${{ inputs.version }}"
          branch: release-${{ inputs.version }}
          base: main
          reviewers: "abhilashlr7"
          assignees: "abhilashlr7"
          draft: false

        
      - name: Print Hello World
        run: echo "Bye World"
