name: Hello World Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  issues: write


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"

      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: mukul-atomicwork
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''
        
      - name: Print Hello World
        run: echo "Bye World"