name: Hello World Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  issues: write


jobs:
  hello:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Print Hello World
        run: echo "Hello World"

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Create new branch
        run: |
          git checkout -b release-asd
          git push origin release-asd
  
      - name: Verify branch creation
        run: git ls-remote --heads origin release-asd

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: release-asd"
          title: "chore: release-asd"
          body: "chore: release-asd"
          branch: release-asd
          base: main
          reviewers: "abhilashlr7"
          assignees: "abhilashlr7"
          draft: false

        
      - name: Print Hello World
        run: echo "Bye World"
