name: "Bot: Manual Build and Deployment"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build and deploy"
        required: true
        default: "main"
      build_version:
        description: "Build version"
        required: true
        default: "1.0.0"

      option1:
        type: boolean
      option2:
        type: boolean
      option3:
        type: boolean

jobs:
  build-info:
    runs-on: ubuntu-latest
    outputs:
      build_branch: ${{ steps.build-info.outputs.build_branch }}
      build_version: ${{ steps.build-info.outputs.build_version }}
      environments: ${{ steps.build-info.outputs.environments }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          mkdir test
          cd test
          pwd
          touch i-will-touch-you-appropriately
          cd ..
          ls
          pwd
          ls test
          mkdir blue
          cd blue

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          pwd
          

  # build:
  #   strategy:
  #     matrix:
  #       environment: ${{fromJson(needs.build-info.outputs.environments)}}
  #   runs-on: ubuntu-latest
  #   needs: [build-info]
  #   steps :
  #     - name: Log Inputs
  #       run: |
  #         echo "Building ${{ inputs.branch }} by @${{ github.actor }}"
  #         echo "Branch: ${{ inputs.branch }}"
  #         echo "Build Version: ${{ inputs.build_version }}-${{matrix.environment.region-suffix}}"
  #         echo "Environment: ${{matrix.environment.env}}"
  #         echo "Region: ${{matrix.environment.region}}"
  #         # set output
  #         echo "build_version=${{ inputs.build_version }}-${{matrix.environment.region-suffix}}" >>$GITHUB_OUTPUT

  # deploy:
  #   strategy:
  #     matrix:
  #       environment: ${{fromJson(needs.build-info.outputs.environments)}}
  #   runs-on: ubuntu-latest
  #   needs: [build-info, build]
  #   steps :
  #     - name: Log Inputs
  #       run: |
  #         echo "Deploying ${{ inputs.build_version }}-${{matrix.environment.region-suffix}} to ${{matrix.environment.env}} by @${{ github.actor }}"
  #         echo "Environment: ${{ inputs.environment }}"
  #         echo "Region: ${{ inputs.region }}"
