name: "Bot: Manual Build and Deployment"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build and deploy"
        required: true
        default: "main"
      build_version:
        description: "Build version"
        required: true
        default: "1.0.0"

jobs:
  build-info:
    runs-on: ubuntu-latest
    outputs:
      build_branch: ${{ steps.build-info.outputs.build_branch }}
      build_version: ${{ steps.build-info.outputs.build_version }}
      environments: ${{ steps.build-info.outputs.environments }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Build info
        id: build-info
        run: |
          build_branch="${{ github.event.inputs.branch }}"
          build_version="${{ github.event.inputs.build_version }}"
          
          echo "build_branch=${build_branch}" >>$GITHUB_OUTPUT
          echo "build_version=${build_version}" >>$GITHUB_OUTPUT
          echo "Build info: branch=${build_branch} version=${build_version}"

          transform_region() {
              input_string=$1
  
              # Split the string by '-' and store the results in an array
              IFS='-' read -r -a parts <<< "$input_string"
  
              # Extract the first part as is, and the first character of the second part
              first_part="${parts[0]}"
              second_part_initial="${parts[1]:0:1}"
  
              # Concatenate the results
              result="${first_part}${second_part_initial}"
  
              echo "$result"
          }

          if [[ "$build_branch" == *beta* ]]; then
            environments='[{"env": "staging", "region": "us-east-1", "region-suffix": "use"}]'
          else
            
            environments='[{"env": "production", "region": "us-east-1", "region-suffix": "use"}, {"env": "production-euw", "region": "eu-west-1", "region-suffix": "euw"}]'
          fi
          echo "environments=${environments}" >>$GITHUB_OUTPUT
          echo "$environments"

  build:
    strategy:
      matrix:
        environment: ${{fromJson(needs.build-info.outputs.environments)}}
    runs-on: ubuntu-latest
    steps :
      - name: Log Inputs
        run: |
          echo "Building ${{ inputs.branch }} by @${{ github.actor }}"
          echo "Branch: ${{ inputs.branch }}"
          echo "Build Version: ${{ inputs.build_version }}-${{matrix.environment.region-suffix}}"
          echo "Environment: ${{matrix.environment.env}}"
          echo "Region: ${{matrix.environment.region}}"
          # set output
          echo "build_version=${{ inputs.build_version }}-${{matrix.environment.region-suffix}}" >>$GITHUB_OUTPUT

  deploy:
    strategy:
      matrix:
        environment: ${{fromJson(needs.build-info.outputs.environments)}}
    runs-on: ubuntu-latest
    steps :
      - name: Log Inputs
        run: |
          echo "Deploying ${{ inputs.build_version }}-${{matrix.environment.region-suffix}} to ${{matrix.environment.env}} by @${{ github.actor }}"
          echo "Environment: ${{ inputs.environment }}"
          echo "Region: ${{ inputs.region }}"